use_frameworks!
platform :ios, "8.0"

target 'kangzehm' do

pod 'SnapKit', '~> 4.0.0' ## 自动布局 https://github.com/SnapKit/SnapKit
pod 'Alamofire', '~> 4.5.1' ## 网络请求, swift版的AFN  https://github.com/Alamofire/Alamofire
pod 'Kingfisher', '~> 4.2.0' ## 轻量级的SDWebImage https://github.com/onevcat/Kingfisher

pod 'SwiftyJSON'  ##JSON 解析类 https://github.com/SwiftyJSON/SwiftyJSON
pod 'MJRefresh'    #快速集成下拉刷新、上拉更多 https://github.com/CoderMJLee/MJRefresh
pod 'IQKeyboardManagerSwift', '~> 5.0.6' ## #解决键盘弹起遮挡 https://github.com/hackiftekhar/IQKeyboardManager
pod 'MBProgressHUD', '~> 1.0.0' # 实现多种加载效果 https://github.com/jdg/MBProgressHUD

pod 'Cosmos', '~> 12.0.1' # 星星评分 https://github.com/marketplacer/Cosmos

pod 'DKImagePickerController' #图片选择器 https://github.com/zhangao0086/DKImagePickerController
pod 'SKPhotoBrowser' #图片浏览器 https://github.com/suzuki-0000/SKPhotoBrowser
pod 'PYSearch'  # 搜索框 https://github.com/ko1o/PYSearch
#pod 'BMPlayer'  # 基于AVPlayer封装的视频播放器  https://github.com/BrikerMan/BMPlayer

#pod 'JPush'  #极光推送
pod 'WechatOpenSDK' #微信SDK

end
